### ISSUE TITLE
No working HD skins.

### ISSUE THREAD

**Issue by GitJhopa** [dzwdz/chat_heads#63] opened 2023-08-17 01:19 UTC
![image](https://github.com/dzwdz/chat_heads/assets/86250668/dc041ade-f14e-4aa1-8985-6a4f5bd48080)
![15828](https://github.com/dzwdz/chat_heads/assets/86250668/4c695904-388a-4c94-bbc5-7110f26f397c)
![4582](https://github.com/dzwdz/chat_heads/assets/86250668/d1496b1d-9ec5-4009-bf0b-9826cf597b1f)
example skins.

**Comment by GitJhopa** [comment] 2023-08-17 01:19
![image](https://github.com/dzwdz/chat_heads/assets/86250668/ff624db1-0ff7-43ed-9888-f519a9c8cfec)
in TAB working,

**Comment by Fourmisain** [comment] 2023-08-17 05:42
Hm... I thought I had an idea of what was going on, but when I tested it, it couldn't reproduce the issue.
![test](https://github.com/dzwdz/chat_heads/assets/8464472/80bc741e-0882-4ae8-834b-82ade24ff3a2)

How are you loading your HD skins?

**Comment by GitJhopa** [comment] 2023-08-17 05:43
> Hm... I thought I had an idea of what was going on, but when I tested it, it couldn't reproduce the issue. ![test](https://user-images.githubusercontent.com/8464472/261207190-80bc741e-0882-4ae8-834b-82ade24ff3a2.png)
> 
> How are you loading your HD skins?

site cristalix.gg

**Comment by Fourmisain** [comment] 2023-08-17 05:44
No, I mean what mod are you using?

**Comment by GitJhopa** [comment] 2023-08-17 05:46
https://drive.google.com/file/d/1Eou10oBqiPKOfjG-6F22sDKh7U6W7Hvq/view?usp=sharing

**Comment by GitJhopa** [comment] 2023-08-17 05:46
This mod allows you to display HD skins, I use it.

**Comment by GitJhopa** [comment] 2023-08-17 05:46
Normal skins are displayed well. But HD is not displayed. Maybe this is due to Slim skins?

**Comment by Fourmisain** [comment] 2023-08-17 07:02
Slim and Classic skins use the same textures, it's just the model that's slightly different.

I just decompiled the skins mod. It doesn't actually do the loading, just the processing of the texture, which I did test and it is working perfectly fine, meaning there has to be something else that's causing this.
I assume you are uploading/setting your skin on cristalix.gg?
If so, then it's most likely the launcher itself that's doing something weird and because it's closed source I don't think I can do anything about it.

Speaking of which, I just looked at the website again and I really have to ask. Where did you even find this?
Google brings up basically nothing and the launcher has a report of it potentially [installing a cryptominer](https://www.virustotal.com/gui/file/29750d9486434d4c2fea75ede7e18672c9e9fd36bf1f611674e0ae0cb46616fe/community)?
Why would you need to install a launcher to play on a minigame server? That makes no sense.
Their "PREMIUM+ donation" is already more expensive than the actual vanilla game and it goes up to 500.000 rubles?!
To me this just screams scam/malware and I would not install this launcher if I were you.

Sorry but I'm closing this as wontfix, because even if the launcher isn't malicious, which I doubt, I don't see a way to fix the underlying issue.

**Closed** 2023-08-17 07:02 UTC

**Comment by GitJhopa** [comment] 2023-08-17 07:06
> Slim and Classic skins use the same textures, it's just the model that's slightly different.
> 
> I just decompiled the skins mod. It doesn't actually do the loading, just the processing of the texture, which I did test and it is working perfectly fine, meaning there has to be something else that's causing this. I assume you are uploading/setting your skin on cristalix.gg? If so, then it's most likely the launcher itself that's doing something weird and because it's closed source I don't think I can do anything about it.
> 
> Speaking of which, I just looked at the website again and I really have to ask. Where did you even find this? Google brings up basically nothing and the launcher has a report of it potentially [installing a cryptominer](https://www.virustotal.com/gui/file/29750d9486434d4c2fea75ede7e18672c9e9fd36bf1f611674e0ae0cb46616fe/community)? Why would you need to install a launcher to play on a minigame server? That makes no sense. Their "PREMIUM+ donation" is already more expensive than the actual vanilla game and it goes up to 500.000 rubles?! To me this just screams scam/malware and I would not install this launcher if I were you.
> 
> Sorry but I'm closing this as wontfix, because even if the launcher isn't malicious, which I doubt, I don't see a way to fix the underlying issue.

In Russia, we are all billionaires, donating 500,000 rubles is still shameful.
