### ISSUE TITLE
Causes Distant Horizons to render dark landscape

### ISSUE THREAD

**Issue by deb0ch** [dzwdz/chat_heads#77] opened 2023-11-27 05:31 UTC
For some obscure (no pun intended) reason, I have no idea how on earth these two mods can even share any scope, but I just spent the last 2h nailing down which of my mods was causing Distant Horizons to render dark LODs and this mod is causing it. The landscape would look like it's at night in the middle of the day.

I don't know how, but it is clear that with ChatHeads: no Distant Horizon, and without ChatHeads: it works perfectly.

I removed all of my mods and added them back one by one to find out, I would never have expected the chat mod to be the culprit so I did it almost last, like WTH 😅 

![image](https://github.com/dzwdz/chat_heads/assets/6248219/4496cda3-6956-4a67-b461-4db90c326a97)

Minecraft 1.20.2
Fabric 0.90.7+1.20.2
Distant Horizons 2.0.1-a-dev
Sodium mc1.20.2-0.5.3
Indium mc1.20.2-0.5.3
ChatHeads 0.10.25

**Comment by Fourmisain** [comment] 2023-11-27 11:00
I can.... reproduce the issue? What the heck indeed!
What confuses me most is that this happens without even a chat head being rendered...?
After reloading the world, the darkness is gone, so it's a one time thing.

Did some quick debugging and the issue seems to be caused by this piece of code, which registers a chat head texture whenever a player skin gets loaded:
https://github.com/dzwdz/chat_heads/blob/b64fe3c96e67f9bd859db5faee4ffc717195546a/common/src/main/java/dzwdz/chat_heads/mixin/HttpTextureMixin.java#L37-L38

I have still no idea why that would cause an issue and how to prevent it.

When it happens, the console is loaded with
> OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Size and/or offset out of range.'

messages.

Sodium and Indium aren't necessary to reproduce the bug, which is good.

I guess some code reading is in order. We should probably ask James if he has any idea what's going on.

**Comment by Fourmisain** [comment] 2023-11-27 13:14
I can't figure out what is happening, so I've opened an issue on the [Distand Horizon issue tracker](https://gitlab.com/jeseibel/distant-horizons/-/issues/590).
Considering just disabling this feature when Distant Horizons is detected if there's no easy solution.

**Comment by Fourmisain** [comment] 2023-12-04 15:43
This is now fixed in Distant Horizons 2.0.1-a.

**Closed by Fourmisain** 2023-12-04 15:43 UTC
