### ISSUE TITLE
screenshot chat notification has wrong player head

### ISSUE THREAD

**Issue by cpm9** [dzwdz/chat_heads#20] opened 2021-11-13 06:05 UTC
If another player says something in chat before you take a screenshot your screenshot will have their player head
![2021-11-12_22 15 27](https://user-images.githubusercontent.com/82549089/141607969-a351e8d5-91cf-4198-aea7-3bd7663859da.png)

chat_heads_forge-0.2.0

**Comment by Fourmisain** [comment] 2021-11-13 11:59
Okay, this is technically not the same as #17 but still a duplicate of #14 which is already fixed.

Please don't spam the issue tracker, check if an issue was already reported before you do and of course try the newest version before any of that.

**Closed by Fourmisain** 2021-11-13 11:59 UTC
