### ISSUE TITLE
Heads aren't showed when seeing messages encrypted by No Chat Reports

### ISSUE THREAD

**Issue by IlyaYezelovsky** [dzwdz/chat_heads#99] opened 2024-07-07 12:22 UTC
Heads are not showed if the message is encrypted with Chat Heads mod.
Maybe it is a bug of No Chat Reports, so I also reported it to No Chat Reports.

**Comment by Fourmisain** [comment] 2024-07-07 17:18
I think I see what the issue is, shouldn't be hard to fix.

Not a bug of No Chat Reports, Chat Heads just doesn't really "catch" the message.

**Comment by Fourmisain** [comment] 2024-07-07 22:45
Fixed in 0.12.7.

Looks like this was only an issue on 1.20.5+ (maybe on 1.20.4, if encryption wasn't broken on that version), so I kept the logic as-is on older versions.

**Closed by Fourmisain** 2024-07-07 22:45 UTC
