### ISSUE TITLE
[Bug or Conflict] After adding various mods, the head is no longer displayed.

### ISSUE THREAD

**Issue by YOMA8338** [dzwdz/chat_heads#95] opened 2024-06-27 06:02 UTC
I will paste the Minecraft log when ChatHeads did not work.
[latest.log](https://github.com/user-attachments/files/16008750/latest.log)

**Comment by Fourmisain** [comment] 2024-06-27 10:26
Hm... I installed nearly every mod in your list but wasn't able to reproduce the issue (yet).

Here's a few mods that _might_ cause issues, even though they didn't for me:
Chat Patches
Figura
SkinTypeFix
Black Bar Concealer
ViaFabric

It's possible the issue is caused by some setting you changed, or it's dependent on the server you're on.
Do the heads work in singleplayer for you?

I'll look this over once again, but you might have to disable some mods and check if the issue disappears.
If you find something, let me know which mods you suspect so I can look into it.

**Comment by Fourmisain** [comment] 2024-06-27 12:08
I installed **all** the mods and I still can't reproduce the issue (at least not in singleplayer)... 🤔

Only difference I found where that some of your mods are slightly out of date, here's the versions I used:
Better Stats `3.11.3` (vs `3.11.2`)
C2ME `0.2.0+alpha.11.106` (vs `alpha.11.98`)
Collective `7.66` (vs `7.64`)
Figura `0.1.4+1.21-dd515624` (vs `2f72a9dc`)
JEI `19.0.0.11` (vs `19.0.0.9`)
Server Resourcepack Checker `1.21-1.2.2` (vs `1.2.1`)
Sound Physics Remastered `1.21-1.4.3` (vs `1.4.2`)
Visuality` 0.7.5+1.21` (vs `0.7.4`)
ThreadTweak I had to patch myself

The [Figura commit history](https://github.com/FiguraMC/Figura/commits/1.21/) shows "Fix Receive Chat Message event firing twice", which isn't in your version you are using and might be related to the issue, so that mod is still a prime candidate.
(Btw, where did you even get that version?  It's not an official release and I can't find an artifact for it either. I got mine on the [latest 1.21 action](https://github.com/FiguraMC/Figura/actions/runs/9621647384), under "Fabric-Artifacts".)

---

So I just tested it on a local test server and was finally able to reproduce the issue!
When I then disabled Figura, the heads reappeared - which looked like that was it.
However, when I reenabled the mod again, the heads were still there - and now I can't seem to reproduce the issue again... 😅

I think that means the issue is load order dependent.
If the conflicting mod loads before Chat Heads, it might work, if it loads after, it might not work (or vice versa).
That makes it really hard to find the actual conflicting mod, since the issue can randomly disappear.

Please give disabling Figura a try. If the issue still appears, we know it can't be that mod.

**Comment by Fourmisain** [comment] 2024-06-27 17:51
I tried changing the Mixin priorities of Chat Heads and still wasn't able to reproduce the issue again, which seems to suggest it's not load order dependent afterall.
I then took a look at the decompilation and found a few more details:
Essential and Black Bar Concealer _might_ be causing an issue when getting the head textures, though unlikely.

Fabric's Message API, Architectury API and JourneyMap (out of all things) may bypass Chat Heads under certain conditions, preventing it from detecting the sender of a message.
Though from the looks of it, all these are meant to filter out certain messages and I don't really think these are the cause, because the issue seems too inconsistent to be a simple logic bug.

---

I found these messages in your log:

> ウェイポイント ネームタグ ChatHeadsの頭が表示されない
ウェイポイントとネームタグは1.20.6で遊んでた時は非表示にならなかったのに

Maybe the issue is actually rendering related?

There's a bunch of OpenGL errors in your log:
> OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error'

I too get similar ones at the same place in the log:
> OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. \<texture\> is not a valid texture name.'

After some investigation I found that those are caused by Remove Reloading Screen.
It looks like something is being rendered before ready to do so.

Try disabling that mod too and see if it helps.

**Comment by YOMA8338** [comment] 2024-06-27 21:05
It seems like it would be easier to get the message across in English than in Japanese as it is 🤣.

Figura used to get it on the Discord server, but I updated it and it now shows up. (I didn't realize there was an update, so thanks for letting me know.)
Updating Figura also fixed the problem of not displaying name tags, lol.
Figura's update log now says "
This build fixes the Nameplate being gone, Camera parented parts not rendering, the Pop Up menu not rendering, a VM error when a mesage with a FIGURA_ FUNCTION in it was gotten with getChatMessage, attempting to use a non-existent post shader effect now errors explicitly, and CHAT_RECEIVE_MESSAGE being called twice for every message, this build also brings Neoforge support with it
with it".
Could the CHAT_RECEIVE_MESSAGE part be the cause?

ThreadTweak was used by rewriting fabric.mod.json of the 1.20.6 version.

**Comment by YOMA8338** [comment] 2024-06-27 21:10
BTW, the waypoints are from JourneyMap and changing the Config fixed it. (Or rather, this message is my chat message).

**Comment by Fourmisain** [comment] 2024-06-28 11:19
> Figura used to get it on the Discord server, but I updated it and it now shows up.
> (...)
> ChatHeads is fixed

That's good news!
I'm still confused why I didn't see the heads that one time and I'm almost starting to doubt myself.
Maybe I was looking at the Chat Patches chat log instead of an actual message, though I'm sure I was scrolling down...
I guess we'll see over time if something is still up.

> Could the CHAT_RECEIVE_MESSAGE part be the cause?

I checked Figura's code and this commit https://github.com/FiguraMC/Figura/commit/7bbe98862a3fcf1de79dec43a445aee619cd8297, and can confirm that yes, this definitely broke Chat Heads before!
Chat Heads temporarily stores the sender of a message and transfers it to the first `GuiMessage` being constructed (when `new GuiMessage` is called).
In the old version, Figura would call `new GuiMessage` twice, essentially removing the owner of the message.
In the new version, I can't find any way how Chat Heads could break, so it should be good to go! 👌

> ChatHeads is fixed, but the duplicate counter for ChatPatches is not....
We need a patch to ChatPatches, lol.

That's apparently already [reported](https://github.com/FiguraMC/Figura/issues/201). Not sure what's breaking it.

Alright, issue appears to be fixed, time to close this issue.
If something breaks again you can just put a comment here and I can reopen the issue if need be.

**Closed by Fourmisain** 2024-06-28 11:19 UTC
