### ISSUE TITLE
Multi-line heads?

### ISSUE THREAD

**Issue by cpm9** [dzwdz/chat_heads#17] opened 2021-11-13 04:27 UTC
The chat heads appear on multiple lines for the same message. Is this intended? I think it looks cluttered and might look better with the head just on the first line of the same message. Of course its your call though. Thanks!
![2021-11-12_21 24 38](https://user-images.githubusercontent.com/82549089/141605659-117c9965-afc6-47fa-9a56-487fad7d49b0.png)

chat_heads_forge-0.2.0

**Comment by Fourmisain** [comment] 2021-11-13 11:56
Duplicate of #5
This is already fixed, use the newest version!

**Closed by Fourmisain** 2021-11-13 11:56 UTC
